/**
 * Legal text carried over VERBATIM from the current site (brief §10: keep the NDPR consent language).
 * TODO(client): Q25 — legal review of these notices before launch. Do not edit wording here without it.
 * Structure: numbered section lines are headings; list items are rendered as lists.
 */
export interface LegalBlock {
  type: "h2" | "p" | "li";
  text: string;
}

export const legalUpdated = "March 11, 2024";

export const privacyPolicy: LegalBlock[] = [
  { type: "p", text: "Last Updated: March 11, 2024" },
  { type: "h2", text: "1.0. Introduction" },
  { type: "p", text: "This Privacy policy constitutes Total Data Ltd.’s commitment to privacy of personal information on all our administrative records, websites, recruitment, professional and other social media platforms, premises and locations of operation." },
  { type: "h2", text: "2.0. Audience" },
  { type: "p", text: "This policy applies to all visitors to our website, clients and potential clients, other individuals who engage all our database applications, services, tools and physical contact with us." },
  { type: "h2", text: "3.0. Purpose of this Policy" },
  { type: "p", text: "It describes your (a natural person or business) privacy rights regarding the collection, use, storage, sharing and protection of your personal information. It applies to our website and all database applications, services, tools and physical contact with us regardless of how you access or use them." },
  { type: "h2", text: "4.0. Personal information:" },
  { type: "h2", text: "4.1. The personal information collected by us may include the following:" },
  { type: "li", text: "Contact information such as your name, date of birth, identification supporting documents (including copies of Driver’s License or Passport Bio Data Page), gender, nationality and race, preferred language, current private and/or business address, telephone or mobile phone number, fax number, email address" },
  { type: "li", text: "Your bank account details" },
  { type: "li", text: "Additional information accessed through your interactions with us; and" },
  { type: "li", text: "When you use our websites, we collect information sent to us by your computer, mobile phone or other electronic access device. The automatically collected information includes but not limited to- data about the pages you access, computer IP address, device ID or unique identifier, device type, geo-location information, computer and connection information, mobile network information, statistics on page views, traffic to and from the sites, referral URL, ad data, standard web log data, still and moving images." },
  { type: "li", text: "Optional information that you voluntarily provide to us." },
  { type: "h2", text: "4.2. Excludes" },
  { type: "li", text: "Information that has been made anonymous so that it does not identify a specific person;" },
  { type: "li", text: "Permanently de-identified information that does not relate or cannot be traced back to you specifically; and" },
  { type: "li", text: "Non-personal statistical information collected and compiled by us and information that you have provided voluntarily in an open, public environment or forum including (without limitation) any blog, social media account, chat room, community, classifieds or discussion board. Because the information has been disclosed in a public forum, it is no longer confidential and does not constitute personal information subject to protection under this policy." },
  { type: "h2", text: "5.0. How we use your personal information:" },
  { type: "p", text: "All information provided to us is used to" },
  { type: "li", text: "Verify identity" },
  { type: "li", text: "Verify qualifications and other claims as part of our recruitment and employment process" },
  { type: "h2", text: "6.0. Consent / Acceptance of Terms" },
  { type: "p", text: "You accept this policy when you give consent upon access to our platforms, fill any of our official documents, or use our services, content or functions offered on our websites, digital platforms or visit any of our physical offices. You may not access our website or use our services if you are younger than 18 years old or do not have legal capacity to conclude legally binding contracts. By accepting this policy, you are deemed to have read, understood, accepted, and agreed to be bound by all its terms." },
  { type: "h2", text: "7.0. Collection from browser" },
  { type: "p", text: "We automatically receive and record Internet usage information on our server logs from your browser, such as your Internet Protocol address (“IP address”), browsing habits, click patterns, version of software installed, system type, screen resolutions, colour capabilities, plug-ins, language settings, cookie preferences, search engine keywords, JavaScript enablement, the content and pages that you access on the website, and the dates and times that you visit the website, paths taken, and time spent on sites and pages within the website (“usage information”). Also note that other websites visited before entering our website might place personal information within your URL during a visit to it, and we have no control over such websites." },
  { type: "h2", text: "7.1. Cookies" },
  { type: "p", text: "When you access our website, we may send one or more cookies (small text files containing a string of alphanumeric characters) to your computer to collect certain usage information. We use session cookies (which disappear after you close your browser) and persistent cookies (which remain after you close your browser and which can be removed manually) and may be used by your browser on subsequent visits to our website. We use information gathered by cookies to improve the website." },
  { type: "h2", text: "7.2. Purpose for collection" },
  { type: "p", text: "We may use any service information and optional information provided by you for such purposes as indicated to you at the time you agree to provide such service information or optional information. We may use your usage information for the purposes described above and to:" },
  { type: "li", text: "Remember your information so that you will not have to re-send it anytime there is a need" },
  { type: "li", text: "Provide any services, which may be useful or beneficial to you; and" },
  { type: "li", text: "Track your entries, submissions, and status of other activities in connection with your usage of the website." },
  { type: "h2", text: "8.0. Disclosure" },
  { type: "h2", text: "8.1. Sharing your information We may share your personal information with:" },
  { type: "li", text: "Our clients for employment purposes" },
  { type: "li", text: "An affiliate, in which case we will seek to require the affiliates to honour this privacy and personal information policy;" },
  { type: "li", text: "Our service providers under contract who help with parts of our business operations (including fraud prevention, bill collection, marketing, technology services). Our contracts dictate that these service providers only use your information in connection with the services they perform for us and not for their own benefit;" },
  { type: "li", text: "State and Federal Tax offices, as permitted by law; and" },
  { type: "li", text: "Banking partners, HMOs as required for inclusion on their list of terminated merchants (in the event that you utilise the services to receive payments and you meet their criteria)." },
  { type: "h2", text: "8.2. Regulators and Law enforcement" },
  { type: "p", text: "8.2.1. If you contact us regarding your experience with using any of our services, we may disclose your personal information as required by law or governmental audit." },
  { type: "p", text: "8.2.2. We may disclose personal information if required:" },
  { type: "li", text: "By a subpoena or court order;" },
  { type: "li", text: "To comply with any law;" },
  { type: "li", text: "To protect the safety of any individual or the general public; and" },
  { type: "li", text: "To prevent violation of our service terms." },
  { type: "h2", text: "8.3. Our Employees" },
  { type: "p", text: "We may need to disclose personal information to our employees that require the personal information to do their jobs." },
  { type: "h2", text: "9.0. Security of Personal Information" },
  { type: "p", text: "Generally, we use computer safeguards such as firewalls and data encryption to protect personal information and we enforce physical access controls to our buildings and files. We authorize access to personal information only for those employees who require it to fulfil their job responsibilities. Our hosting company will host our website in a secure server environment that uses a firewall and other advanced security measures to prevent interference or access from outside intruders. We authorize access to personal information only for those employees who require it to fulfil their job responsibilities." },
  { type: "h2", text: "10.0. Data Accuracy" },
  { type: "p", text: "We will try to keep the personal information we collect as accurate, complete and up to date as is necessary for the purposes explicitly defined in this policy." },
  { type: "h2", text: "11.0. Retention of personal information" },
  { type: "p", text: "We will only retain your personal information for as long as we determine is necessary to fulfil the purposes explicitly set out in this policy, unless:" },
  { type: "li", text: "Retention of the record is required or authorised by law; or" },
  { type: "li", text: "The period of retention shall be 5 years" },
  { type: "li", text: "You have consented to the retention of the record." },
  { type: "p", text: "During the period of retention, we will continue to abide by our obligations." },
  { type: "h2", text: "12.0. Updating or removing" },
  { type: "p", text: "We make good faith efforts to provide you with access to your personal information and either to correct this data if it is inaccurate or to delete such data at your request if it is not otherwise required to be retained by law or for legitimate business purposes." },
  { type: "h2", text: "13.0. Limitation" },
  { type: "p", text: "We are not responsible for, give no warranties, nor make any representations in respect of the privacy policies or practices of linked or any third-party websites." },
  { type: "h2", text: "14.0. Changes" },
  { type: "p", text: "We may change the terms of this policy at any time. We will notify you of any changes by placing a notice in a prominent place on the website, at our premises or by email. If you do not agree with the change you must stop using the service. If you continue to use the services following notification of a change to the terms, the changed terms will apply to you and you will be deemed to have accepted such terms." },
  { type: "h2", text: "15.0 Data Subject Rights" },
  { type: "li", text: "1. The right to be informed: This means anyone processing your personal data must make clear what they are processing, why and who else the data may be passed to." },
  { type: "li", text: "2. The right of access: This is your right to see what data is held about you by Total Data Limited" },
  { type: "li", text: "3. The right to rectification: This is your right to have your data corrected or amended if what is held is incorrect in some way." },
  { type: "li", text: "4. The right to erasure: Under certain circumstances you may ask for your personal data to be deleted. This is also called “the Right to be Forgotten”. This would apply if your personal data is no longer required for the purposes it was collected for, or your consent for the processing of that data has been withdrawn, or your personal data has been unlawfully processed." },
  { type: "li", text: "5. The right to restrict processing: This gives you the right to ask for a temporary halt on the processing of your personal data, such as in the case where a dispute or legal case must be concluded, or the data is been corrected." },
  { type: "li", text: "6. The right to data portability: You have the right to ask for any data supplied directly to Total Data Limited to be provided in a structured, commonly used, and machine-readable format." },
  { type: "li", text: "7. The right to object: You have the right to object to further processing of your data which is inconsistent with the primary purpose for which it was collected, including profiling, automation and direct or digital marketing." },
  { type: "li", text: "8. Rights in relation to automated decision making and profiling: You have the right not to be subject to a decision based solely on automated processing" },
  { type: "h2", text: "16.0 Enquiries" },
  { type: "p", text: "If you have any questions or concerns arising from this privacy & personal information policy, the way in which we handle personal information or to exercise any of your rights, please contact us at: info@totaldatalimited.com; 08185461010" },
];

export const cookiesPolicy: LegalBlock[] = [
  { type: "p", text: "Last Updated: March 11, 2024" },
  { type: "h2", text: "1.0. Introduction" },
  { type: "p", text: "This cookies policy explains how Total Data Limited uses cookies and other similar technologies to collect information about the way you use this website. Total Data Limited reserves the right to make changes to this cookies policy at any time and for any reason. Total Data Limited will alert you about any changes by updating the “Last Updated” date of this cookies policy. Any changes or modifications shall be effective immediately upon posting the updated cookies policy on this website." },
  { type: "h2", text: "2.0. Scope of this policy" },
  { type: "p", text: "This Policy applies as between you, the User of this Website and Total Data Limited, the owner and provider of this website. It does not extend to any websites that can be accessed from this website including, but not limited to, any links we may provide to social media websites." },
  { type: "h2", text: "3.0. What are cookies?" },
  { type: "p", text: "Cookies are text files with small pieces of data — like a username and password — that are used to identify your computer as you use a computer network. Specific cookies known as HTTP cookies are used to identify specific users and improve your web browsing experience." },
  { type: "h2", text: "4.0. How do we use cookies?" },
  { type: "p", text: "Information supplied to us using cookies helps us to analyse the profile of our visitors and provide you with a better online experience. When you submit data through a form, such as those found on contact pages or comment forms, cookies may be set to remember your user details for future correspondence. Total Data Limited uses cookies to track how you use our site by providing usage statistics on things such as how long you spend on the site and the pages that you visit. Cookies are also used to serve advertisements to you based upon your browsing history and previous visits to the site. Whilst this information on its own does not usually constitute your Personal Data (see our Privacy Policy/Notice for further details on how we process such information in this regard), we may combine the information we collect by cookies with your Personal Data that we have collected from you in order to learn more about how you use the site, improve our services and continue to produce engaging content." },
  { type: "h2", text: "5.0. Cookies we use" },
  { type: "p", text: "To help you understand the different types of cookies we use and what they do, Total Data Limited has conducted a full audit of our site and grouped cookies into different categories." },
  { type: "li", text: "Strictly necessary cookies: 'Strictly necessary' cookies let you move around the website and use essential features such as accessing secure areas of the website and identifying you as being logged in. These cookies don't gather any information about you that could be used for marketing or remembering where you've been on the internet." },
  { type: "li", text: "Performance cookies: We use these cookies to collect information about how visitors use our website, including details of the site where the visitor has come from and the total number of times a visitor has been to our website. By using our website, you agree that we can place this type of cookies on your device. We use the information to improve our website and enhance the experience of visitors." },
  { type: "li", text: "Functionality cookies: These cookies allow the website to remember choices you make [such as your username, language, or the region you are in] and provide enhanced, more personal features. These cookies can also be used to remember changes you have made to text size, fonts, and other parts of web pages that you can customise." },
  { type: "li", text: "Targeting cookies: The cookies are usually placed either directly by third party advertising networks and from time to time, the cookies collect information about your browsing habits in order to deliver adverts more relevant to you and your interests." },
  { type: "h2", text: "6.0. Disabling Cookies" },
  { type: "p", text: "You can block cookies by activating the setting on your browser that allows you to refuse the setting of all or some cookies. However, if you use your browser settings to block all cookies (including essential cookies) you may not be able to access all or parts of our site." },
];
